Fix ts-scenario TypeScript transpile failure (#675)
ts-scenario tests failed with Node 16 and 18 only, with the following error:

TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.

The fix is to explicitly specify the location of the tsconfig.json file (containing the required TypeScript compiler configuration) for ts-node using the TS_NODE_PROJECT environment variable.

Also disable runtime type checking in ts-node using the SWC transpiler to provide a performance improvement.

Signed-off-by: Mark S. Lewis <Mark.S.Lewis@outlook.com>